# Generated by Django 4.2.2 on 2023-06-21 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevator_id', models.BigIntegerField()),
                ('is_operational', models.BooleanField(default=True)),
                ('is_busy', models.BooleanField(default=False)),
                ('current_floor', models.IntegerField(default=1)),
                ('is_open', models.BooleanField(default=False)),
                ('direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('stopped', 'Stopped')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ElevatorSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('no_of_elevators', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('destination_floor', models.IntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator.elevator')),
            ],
        ),
        migrations.AddField(
            model_name='elevator',
            name='elevator_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator.elevatorsystem'),
        ),
    ]
