# Generated by Django 4.2.2 on 2023-06-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0002_request_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
